<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <script>
            const PENDING = 'PENDING'
            const FULLFILLED = 'FULLFILLED'
            const REJECTED = 'REJECTED'

            const resolvePromise = (promise2, x, resolve, reject) => {
                // 解决循环调用
                if (promise2 === x) {
                    return reject(new TypeError('Chaining cycle detected for promise #<Promise>'))
                }

                let called
                if ((typeof x === 'object' && x !== null) || typeof x === 'function') {
                    try {
                        let then = x.then
                        if (typeof then === 'function') {
                            then.call(
                                x,
                                (y) => {
                                    if (called) return
                                    called = true
                                    resolveProidure(promise2, y, resolve, reject)
                                },
                                (r) => {
                                    if (called) return
                                    called = true
                                    reject(r)
                                }
                            )
                        } else {
                            resolve(x)
                        }
                    } catch (err) {
                        if (called) return
                        called = true
                        reject(err)
                    }
                } else {
                    resolve(x)
                }
            }
            // write my promise
            class MyPromise {
                constructor(executor) {
                    this.status = PENDING
                    // 存放成功状态的值，默认为 undefined
                    this.value = undefined
                    // 存放失败状态的值，默认为 undefined
                    this.reason = undefined
                    this.onResolvedCallbacks = []
                    this.onRejectedCallbacks = []

                    let resole = (value) => {
                        if (this.status === PENDING) {
                            this.status = FULLFILLED
                            this.value = value
                            this.onResolvedCallbacks.forEach((fn) => fn())
                        }
                    }
                    let reject = (reason) => {
                        if (this.status === PENDING) {
                            this.status = REJECTED
                            this.reason = reason
                            this.onRejectedCallbacks.forEach((fn) => fn())
                        }
                    }

                    try {
                        executor(resole, reject)
                    } catch (error) {
                        reject(error)
                    }
                }

                then(onFulfilled, onRejected) {
                    //解决 onFufilled，onRejected 没有传值的问题
                    onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : (value) => value
                    onRejected =
                        typeof onRejected === 'function'
                            ? onRejected
                            : (reason) => {
                                  throw reason
                              }
                    let promise2 = new MyPromise((resolve, reject) => {
                        if (this.status === FULLFILLED) {
                            setTimeout(() => {
                                try {
                                    let x = onFulfilled(this.value)
                                    resolvePromise(promise2, x, resolve, reject)
                                } catch (e) {
                                    reject(e)
                                }
                            }, 0)
                        }
                        if (this.status === REJECTED) {
                            setTimeout(() => {
                                try {
                                    let x = onRejected(this.reason)
                                    resolvePromise(promise2, x, resolve, reject)
                                } catch (e) {
                                    reject(e)
                                }
                            }, 0)
                        }

                        if (this.status === PENDING) {
                            this.onResolvedCallbacks.push(() => {
                                setTimeout(() => {
                                    try {
                                        let x = onFulfilled(this.value)
                                        resolvePromise(promise2, x, resolve, reject)
                                    } catch (e) {
                                        reject(e)
                                    }
                                }, 0)
                            })

                            this.onRejectedCallbacks.push(() => {
                                setTimeout(() => {
                                    try {
                                        let x = onRejected(this.reason)
                                        resolvePromise(promise2, x, resolve, reject)
                                    } catch (e) {
                                        reject(e)
                                    }
                                }, 0)
                            })
                        }
                    })
                    return promise2
                }
                catch() {}

                finally() {}
                static resolve(data) {
                    return new MyPromise((resolve, reject) => {
                        resolve(data)
                    })
                }
                static reject(reason) {
                    return new MyPromise((resolve, reject) => {
                        reject(reason)
                    })
                }
            }

            const promise = new MyPromise((resolve, reject) => {
                resolve('失败')
            })
                .then((res) => {
                    console.log(res)
                    return '成功'
                })
                .then()
                .then(
                    (data) => {
                        console.log(data)
                    },
                    (err) => {
                        console.log('err', err)
                    }
                )

            MyPromise.prototype.race = function (arr) {
                return new MyPromise((resolve, reject) => {
                    for (let i = 0; i < arr.length; i++) {
                        arr[i].then(resolve, reject)
                    }
                })
            }

            MyPromise.prototype.all = function (iterable) {
                let arr = Array.from(iterable)
                let count = 0
                let results = []

                return new MyPromise((resolve, reject) => {
                    for (let i = 0; i < arr.length; i++) {
                        MyPromise.resolve(arr[i])
                            .then((res) => {
                                results[i] = res
                                count++
                                if (count === arr.length) {
                                    resolve(results)
                                }
                            })
                            .catch((err) => {
                                reject(err)
                            })
                    }
                })
            }
            MyPromise.prototype.catch = function (errCallback) {
                return this.then(null, errCallback)
            }
            MyPromise.prototype.finally = function (callback) {
                return this.then(
                    (value) => {
                        return MyPromise.resolve(callback()).then(() => value)
                    },
                    (reason) => {
                        return MyPromise.resolve(callback()).then(() => {
                            throw reason
                        })
                    }
                )
            }
        </script>
    </body>
</html>
